services:
  db:
    image: postgres:15
    container_name: auth_postgres
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: auth_service
    #depends_on:
    #  - db
    ports:
      - "8080:8080"
    #env_file:
    #  - .env
    volumes:
      - .:/app
    working_dir: /app
    command: ["go", "run", "cmd/app/main.go"]

volumes:
  db_data:
